""" version which can be consumed from within the module """
VERSION_STR = "0.0.3"
DESCRIPTION = "pygooglecloud helps you with command line interaction with gcp"
APP_NAME = "pygooglecloud"
LOGGER_NAME = "pygooglecloud"
